# Generated by Django 3.2.16 on 2023-03-28 00:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_name'),
        ('account', '0005_alter_account_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AlterField(
            model_name='account',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2023, 3, 27, 20, 17, 25, 145826)),
        ),
    ]
