# Generated by Django 3.2.16 on 2023-03-28 00:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20230327_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2023, 3, 27, 20, 31, 52, 927068)),
        ),
    ]
