# Generated by Django 3.2.16 on 2023-03-28 00:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_account_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2023, 3, 27, 20, 32, 14, 63946)),
        ),
    ]
