# Generated by Django 3.2.16 on 2023-03-29 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_account_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='startDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
