# Generated by Django 3.2.16 on 2023-04-02 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_account_startdate'),
        ('time_entry', '0002_alter_timeentry_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
    ]
