# Generated by Django 3.2.16 on 2023-04-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_entry', '0004_alter_timeentry_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='hoursWorked',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
