# Generated by Django 3.2.16 on 2023-04-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_entry', '0005_alter_timeentry_hoursworked'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='start_time',
            field=models.TimeField(default=None, null=True),
        ),
    ]
