# Generated by Django 3.2.16 on 2023-04-09 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_entry', '0005_alter_timeentry_hoursworked'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='punchInTime',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='punchOutTime',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
